apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - name: example-application
        image: <image-name>:<tag>
        ports:
        - containerPort: 8080

